/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smscenter.gui;

import java.util.List;
import javax.swing.SwingUtilities;
import smscenter.database.Database;

/**
 *
 * @author chtheis
 */
public class IncomingPanel extends BasePanel {

    /**
     * Creates new form Incoming
     */
    public IncomingPanel(Database database) {
        super(database);
        initComponents();
    }
    
    @Override
    public void update() {
        synchronized (incomingTable) {
            List<Object[]> list;

            list = database.getIncomingMessages(start, count);

            updateRows(list, incomingTable);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        senderTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textTextArea = new javax.swing.JTextArea();
        statusTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        startSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        countSpinner = new javax.swing.JSpinner();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("smscenter/gui/resources/SMSCenter"); // NOI18N
        jLabel2.setText(bundle.getString("Status:")); // NOI18N

        jLabel3.setText(bundle.getString("Sender:")); // NOI18N

        senderTextField.setEditable(false);
        senderTextField.setText("jTextField1");

        jLabel4.setText(bundle.getString("Date:")); // NOI18N

        dateTextField.setEditable(false);
        dateTextField.setText("jTextField2");

        jLabel5.setText(bundle.getString("Text:")); // NOI18N

        textTextArea.setEditable(false);
        textTextArea.setColumns(40);
        textTextArea.setRows(5);
        jScrollPane2.setViewportView(textTextArea);

        statusTextField.setEditable(false);
        statusTextField.setText("jTextField1");

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusTextField)
                    .addComponent(dateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(senderTextField))
                .addContainerGap())
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(senderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        incomingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Row", "ID", "Status", "Sender", "Text", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        incomingTable.setFillsViewportHeight(true);
        incomingTable.getTableHeader().setReorderingAllowed(false);
        incomingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incomingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(incomingTable);
        incomingTable.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("ID")); // NOI18N
        incomingTable.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("Status")); // NOI18N
        incomingTable.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("Sender")); // NOI18N
        incomingTable.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("Text")); // NOI18N
        incomingTable.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("Date")); // NOI18N

        jLabel1.setText(bundle.getString("Selection:")); // NOI18N

        deleteButton.setText(bundle.getString("Delete")); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel6.setText(bundle.getString("Start:")); // NOI18N

        startSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, null, Integer.valueOf(50)));
        startSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                startSpinnerStateChanged(evt);
            }
        });

        jLabel7.setText(bundle.getString("Count:")); // NOI18N

        countSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(50), Integer.valueOf(10), null, Integer.valueOf(10)));
        countSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                countSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(countSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(deleteButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        new Thread(new Runnable() {

            @Override
            public void run() {
                synchronized (incomingTable) {
                    int[] rows = incomingTable.getSelectedRows();

                    for (int i = rows.length; i-- > 0; ) {
                        int id = ((Integer) incomingTable.getModel().getValueAt(rows[i], 1)).intValue();
                        database.removeIncomingMessage(id);
                    }
                }
                
                SwingUtilities.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        update();
                    }
                });
            }            
        }).start();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void incomingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incomingTableMouseClicked
        if (evt.getClickCount() != 2)
            return;
        
        int row = incomingTable.rowAtPoint(evt.getPoint());
        statusTextField.setText(incomingTable.getModel().getValueAt(row, 2).toString());
        senderTextField.setText(incomingTable.getModel().getValueAt(row, 3).toString());
        dateTextField.setText(incomingTable.getModel().getValueAt(row, 5).toString());
        textTextArea.setText(incomingTable.getModel().getValueAt(row, 4).toString());
        
        javax.swing.JOptionPane.showMessageDialog(this, detailPanel);
    }//GEN-LAST:event_incomingTableMouseClicked

    private void startSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_startSpinnerStateChanged
        start = Integer.parseInt(startSpinner.getValue().toString());
        update();
    }//GEN-LAST:event_startSpinnerStateChanged

    private void countSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_countSpinnerStateChanged
        count = Integer.parseInt(countSpinner.getValue().toString());
        start = (start / count) * count;
        ((javax.swing.SpinnerNumberModel) startSpinner.getModel()).setStepSize(count);
        update();
    }//GEN-LAST:event_countSpinnerStateChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner countSpinner;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel detailPanel;
    private final javax.swing.JTable incomingTable = new javax.swing.JTable();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField senderTextField;
    private javax.swing.JSpinner startSpinner;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JTextArea textTextArea;
    // End of variables declaration//GEN-END:variables

    int start = 0;
    int count = 200;
}
