package smscenter.gui;

import java.text.MessageFormat;
import java.util.Locale;
import java.awt.Color;


public class SMSConfigurationPanel extends javax.swing.JPanel {

    /**
     * Creates new form SMSConfigurationPanel
     */
    public SMSConfigurationPanel() {
        initComponents();
        
    }
    
    public void setWelcomeMsg(String welcomeMsg) {
        welcomeMsgText.setText(welcomeMsg);
                
        int remaining = 160 - welcomeMsgText.getText().length();
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("smscenter/gui/resources/SMSCenter"); 
        String msg = new MessageFormat(bundle.getString("remainingCharLabel"), Locale.ENGLISH).format(new Object[] {remaining >= 0 ? remaining : ""});
        remainingCharLabel.setText(msg);        
    }
    
    public String getWelcomeMsg() {
        return welcomeMsgText.getText();
    }
    
    public void setSponsorLine(String sponsorLine) {
        sponsorLineText.setText(sponsorLine);        
    }
    
    public String getSponsorLine() {
        return sponsorLineText.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        welcomeMsgText = new javax.swing.JTextArea();
        remainingCharLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sponsorLineText = new javax.swing.JTextField();

        jLabel5.setText("Welcome Msg:");

        welcomeMsgText.setColumns(20);
        welcomeMsgText.setRows(5);
        welcomeMsgText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                welcomeMsgTextKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(welcomeMsgText);

        remainingCharLabel.setText("160");

        jLabel6.setText("Sponsor Line:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remainingCharLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(sponsorLineText))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remainingCharLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sponsorLineText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void welcomeMsgTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_welcomeMsgTextKeyTyped
        int remaining = 160 - welcomeMsgText.getText().length();
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("smscenter/gui/resources/SMSCenter");
        String msg = new MessageFormat(bundle.getString("remainingCharLabel"), Locale.ENGLISH).format(new Object[] {remaining});
        remainingCharLabel.setText(msg);
        if (remaining < 0)
            remainingCharLabel.setForeground(Color.red);
        else
            remainingCharLabel.setForeground(Color.black);

        remainingCharLabel.repaint();
    }//GEN-LAST:event_welcomeMsgTextKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel remainingCharLabel;
    private javax.swing.JTextField sponsorLineText;
    private javax.swing.JTextArea welcomeMsgText;
    // End of variables declaration//GEN-END:variables
}
