/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smscenter.gui.settings;

import java.util.Properties;

/**
 *
 * @author chtheis
 */
public class BulkSmsHttpSettingsPanel extends SettingsPanel {

    private BulkSmsHttpSettings settings;
    
    /**
     * Creates new form BulkSmsSettingsPanel
     */
    public BulkSmsHttpSettingsPanel(BulkSmsHttpSettings settings) {
        this.settings = settings;
        initComponents();
    }


    @Override
    public void loadProperties(Properties props) {
        usernameTextField.setText(settings.getUsername());
        passwordTextField.setText(settings.getPassword());
        regionComboBox.setSelectedItem(settings.getRegion());
        inboundCheckbox.setSelected(settings.isInbound());
        outboundCheckbox.setSelected(settings.isOutbound());  
        descriptionTextField.setText(settings.getDescription());
    }

    @Override
    public void writeProperties(Properties props) {
        settings.setUsername(usernameTextField.getText());
        settings.setPassword(passwordTextField.getText());
        if (regionComboBox.getSelectedItem() != null)
            settings.setRegion(regionComboBox.getSelectedItem().toString());
        settings.setInbound(inboundCheckbox.isSelected());
        settings.setOutbound(outboundCheckbox.isSelected());
        settings.setDescription(descriptionTextField.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        regionComboBox = new javax.swing.JComboBox();
        inboundCheckbox = new javax.swing.JCheckBox();
        outboundCheckbox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("smscenter/gui/resources/SMSCenter"); // NOI18N
        jLabel1.setText(bundle.getString("Username:")); // NOI18N

        jLabel2.setText(bundle.getString("Password:")); // NOI18N

        jLabel3.setText(bundle.getString("Region:")); // NOI18N

        regionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Germany", "International" }));

        inboundCheckbox.setText(bundle.getString("Inbound")); // NOI18N
        inboundCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboundCheckboxActionPerformed(evt);
            }
        });

        outboundCheckbox.setText(bundle.getString("Outbound")); // NOI18N
        outboundCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outboundCheckboxActionPerformed(evt);
            }
        });

        jLabel4.setText(bundle.getString("Description:")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTextField)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(inboundCheckbox)
                        .addGap(18, 18, 18)
                        .addComponent(outboundCheckbox))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionTextField)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passwordTextField, regionComboBox, usernameTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(regionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inboundCheckbox)
                    .addComponent(outboundCheckbox))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inboundCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboundCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inboundCheckboxActionPerformed

    private void outboundCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outboundCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outboundCheckboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JCheckBox inboundCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox outboundCheckbox;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JComboBox regionComboBox;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
