/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smscenter.gui.settings;

import java.util.Properties;

/**
 *
 * @author chtheis
 */
public class DatabaseSettingsPanel extends SettingsPanel {

    DatabaseSettings database;
    
    /**
     * Creates new form DatabaseSettingsPanel
     */
    public DatabaseSettingsPanel() {
        initComponents();
    }
    
    
    @Override
    public void loadProperties(Properties props) {
        database = Settings.readDatabase(props);
        
        serverTextField.setText(database.getServer());
        databaseTextField.setText(database.getDatabase());
        windowsAuthenticationCheckBox.setSelected(database.isWindowsAuth());
        userTextField.setText(database.getUser());
        passwordTextField.setText(database.getPassword());
        batchSizeSpinner.setValue(database.getBatch_size());
        updateOutboundOnStatusReport.setSelected(database.isUpdateOutboundOnStatusreport());
        
        userTextField.setEnabled(!database.isWindowsAuth());
        passwordTextField.setEnabled(!database.isWindowsAuth());          
    }
    
    
    @Override
    public void writeProperties(Properties props) {
        database.setServer(serverTextField.getText());
        database.setDatabase(databaseTextField.getText());
        database.setWindowsAuth(windowsAuthenticationCheckBox.isSelected());
        database.setUser(userTextField.getText());
        database.setPassword(passwordTextField.getText());        
        database.setBatch_size(Integer.parseInt(batchSizeSpinner.getValue().toString()));
        database.setUpdateOutboundOnStatusreport(updateOutboundOnStatusReport.isSelected());
        
        Settings.writeDatabase(database, props);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serverTextField = new javax.swing.JTextField();
        databaseTextField = new javax.swing.JTextField();
        windowsAuthenticationCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        batchSizeSpinner = new javax.swing.JSpinner();
        updateOutboundOnStatusReport = new javax.swing.JCheckBox();
        passwordTextField = new javax.swing.JPasswordField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("smscenter/gui/resources/SMSCenter"); // NOI18N
        jLabel1.setText(bundle.getString("Server:")); // NOI18N

        jLabel2.setText(bundle.getString("Database:")); // NOI18N

        serverTextField.setText("(local)");

        windowsAuthenticationCheckBox.setText(bundle.getString("Windows Authentication")); // NOI18N
        windowsAuthenticationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowsAuthenticationCheckBoxActionPerformed(evt);
            }
        });

        jLabel3.setText(bundle.getString("User:")); // NOI18N

        jLabel4.setText(bundle.getString("Password:")); // NOI18N

        jLabel5.setText(bundle.getString("Batch size:")); // NOI18N

        batchSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(50), Integer.valueOf(10), null, Integer.valueOf(10)));

        updateOutboundOnStatusReport.setText(bundle.getString("Update outbound on status report")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)
                                .addComponent(userTextField))
                            .addComponent(serverTextField)
                            .addComponent(databaseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(windowsAuthenticationCheckBox)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordTextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateOutboundOnStatusReport)
                            .addComponent(batchSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(serverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(databaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(windowsAuthenticationCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batchSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateOutboundOnStatusReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void windowsAuthenticationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsAuthenticationCheckBoxActionPerformed
        userTextField.setEnabled(!windowsAuthenticationCheckBox.isSelected());
        passwordTextField.setEnabled(!windowsAuthenticationCheckBox.isSelected());
    }//GEN-LAST:event_windowsAuthenticationCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner batchSizeSpinner;
    private javax.swing.JTextField databaseTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTextField serverTextField;
    private javax.swing.JCheckBox updateOutboundOnStatusReport;
    private javax.swing.JTextField userTextField;
    private javax.swing.JCheckBox windowsAuthenticationCheckBox;
    // End of variables declaration//GEN-END:variables
}
